openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example with allof and additional properties
paths:
  /check:
    get:
      summary: Return example
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/exampleSchemaWithAdditionalProperties"
components:
  schemas:
    exampleSchemaWithAdditionalProperties:
      type: object
      required:
        - additionalProperty
      properties:
        additionalProperty:
          type: string
      allOf:
        - $ref: "#/components/schemas/exampleSchema"
    exampleSchema:
      required:
        - baseProperty
      properties:
        baseProperty:
          type: string
